# Generated by Django 3.0 on 2021-02-22 11:49

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields.related


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LanCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='відсутній', max_length=200, verbose_name='бренд мережевої плати')),
                ('model', models.CharField(default='відсутній', max_length=200, verbose_name='модель мережевої плати')),
                ('serial_number', models.CharField(default='відсутній', max_length=200, unique=True, verbose_name='серійний номер')),
            ],
            options={
                'verbose_name': 'Мережева плата',
                'verbose_name_plural': 'Мережеві плати',
            },
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='відсутній', max_length=200, verbose_name='бренд материнської плати')),
                ('model', models.CharField(default='відсутній', max_length=200, verbose_name='модель материнської плати')),
                ('serial_number', models.CharField(default='відсутній', max_length=200, unique=True, verbose_name='серійний номер')),
                ('form_factor', models.CharField(choices=[('не вказано', ''), ('ATX', 'ATX'), ('microATX', 'microATX'), ('Mini-ITX', 'Mini-ITX'), ('Nano-ITX', 'Nano-ITX'), ('Pico-ITX', 'Pico-ITX')], max_length=20)),
                ('type_ram_slot', models.CharField(choices=[('не вказано', ''), ('DIMM', 'DIMM'), ('RIMM', 'RIMM'), ('DDR DIMM', 'DDR DIMM'), ('DDR2', 'DDR2'), ('DDR3', 'DDR3')], default='не вказано', max_length=20)),
                ('integrated_graphics', models.BooleanField(default=False)),
                ('integrated_sound_card', models.BooleanField(default=False)),
                ('integrated_lan_card', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Материнська плата',
                'verbose_name_plural': 'Материнські плати',
            },
        ),
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='відсутній', max_length=200, verbose_name='бренд блока живлення')),
                ('model', models.CharField(default='відсутній', max_length=200, verbose_name='модель блока живлення')),
                ('serial_or_inventory_number', models.CharField(default='відсутній', max_length=200, unique=True, verbose_name='серійний або інвентарний номер')),
                ('power_consumption', models.IntegerField(default=0, verbose_name='споживана потужність')),
            ],
            options={
                'verbose_name': 'Блок живлення',
                'verbose_name_plural': 'Блоки живлення',
            },
        ),
        migrations.CreateModel(
            name='SoundCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='відсутній', max_length=200, verbose_name='бренд звукової плати')),
                ('model', models.CharField(default='відсутній', max_length=200, verbose_name='модель звукової плати')),
                ('serial_number', models.CharField(default='відсутній', max_length=200, verbose_name='серійний номер')),
            ],
            options={
                'verbose_name': 'Звукова плата',
                'verbose_name_plural': 'Звукові плати',
            },
        ),
        migrations.CreateModel(
            name='VideoCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='відсутній', max_length=200, verbose_name='бренд відеокарти')),
                ('model', models.CharField(default='відсутній', max_length=200, verbose_name='модель відеокарти')),
                ('serial_number', models.CharField(default='відсутній', max_length=200, unique=True, verbose_name='серійний номер')),
                ('memory_size', models.IntegerField(default=0, verbose_name="обсяг пам'яті")),
            ],
            options={
                'verbose_name': 'Відеокарта',
                'verbose_name_plural': 'Відеокарти',
            },
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=200, unique=True, verbose_name='інвентарний номер')),
                ('floor', models.IntegerField(verbose_name='номер поверху')),
                ('room', models.IntegerField(verbose_name='номер кабінету')),
                ('place', models.IntegerField(blank=True, default=0, null=True, verbose_name='номер учбового місця')),
                ('lan_card', models.ForeignKey(null=True, on_delete=django.db.models.fields.related.OneToOneField, to='IT_items.LanCard')),
                ('motherboard', models.ForeignKey(null=True, on_delete=django.db.models.fields.related.OneToOneField, to='IT_items.Motherboard')),
                ('power_supply', models.ForeignKey(null=True, on_delete=django.db.models.fields.related.OneToOneField, to='IT_items.PowerSupply')),
                ('sound_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IT_items.SoundCard')),
                ('video_card', models.ForeignKey(null=True, on_delete=django.db.models.fields.related.OneToOneField, to='IT_items.VideoCard')),
            ],
            options={
                'verbose_name': "Персональний комп'ютор",
                'verbose_name_plural': "Персональні комп'ютори",
            },
        ),
    ]
