# Generated by Django 3.0 on 2021-01-05 19:51

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='відсутній', max_length=200, verbose_name='бренд материнської плати')),
                ('model', models.CharField(default='відсутній', max_length=200, verbose_name='модель материнської плати')),
                ('serial_number', models.CharField(max_length=200, verbose_name='серійний номер')),
                ('integrated_graphics', models.BooleanField(default=False)),
                ('integrated_sound_card', models.BooleanField(default=False)),
                ('integrated_lan_card', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Материнська плата',
                'verbose_name_plural': 'Материнські плати',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='відсутній', max_length=200, verbose_name='бренд блока живлення')),
                ('model', models.CharField(default='відсутній', max_length=200, verbose_name='модель блока живлення')),
                ('serial_or_inventory_number', models.CharField(default='відсутній', max_length=200, unique=True, verbose_name='серійний або інвентарний номер')),
                ('power_consumption', models.IntegerField(verbose_name='споживана потужність')),
            ],
            options={
                'verbose_name': 'Блок живлення',
                'verbose_name_plural': 'Блоки живлення',
            },
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=200, unique=True, verbose_name='інвентарний номер')),
                ('floor', models.IntegerField(verbose_name='номер поверху')),
                ('room', models.IntegerField(verbose_name='номер кабінету')),
                ('place', models.IntegerField(blank=True, default=0, null=True, verbose_name='номер учбового місця')),
                ('motherboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IT_items.Motherboard')),
            ],
            options={
                'verbose_name': "Персональний комп'ютор",
                'verbose_name_plural': "Персональні комп'ютори",
            },
        ),
    ]
