# Generated by Django 3.0 on 2021-03-14 10:51

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('IT_items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='відсутній', max_length=200, verbose_name='бренд мережевої плати')),
                ('model', models.CharField(default='відсутній', max_length=200, verbose_name='модель мережевої плати')),
                ('serial_number', models.CharField(default='відсутній', max_length=200, unique=True, verbose_name='серійний номер')),
            ],
            options={
                'verbose_name': 'Мережева плата',
                'verbose_name_plural': 'Мережеві плати',
            },
        ),
        migrations.CreateModel(
            name='OpticalDrive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='відсутній', max_length=200, verbose_name='бренд оптичного накопичувача')),
                ('model', models.CharField(default='відсутній', max_length=200, verbose_name='модель оптичного накопичувача')),
                ('serial_number', models.CharField(default='відсутній', max_length=200, verbose_name='серійний номер')),
                ('type_drive', models.CharField(choices=[('не вказано', ''), ('DVD', 'DVD'), ('CD', 'CD'), ('CD-R', 'CD-R'), ('CD-RM', 'CD-RM')], default='не вказано', max_length=20)),
                ('type_connector', models.CharField(choices=[('SATA', 'SATA'), ('PATA', 'PATA')], default='не вказано', max_length=20)),
            ],
            options={
                'verbose_name': 'Оптичний накопичувач',
                'verbose_name_plural': 'Оптичні накопичувачі',
            },
        ),
        migrations.CreateModel(
            name='SoundCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='відсутній', max_length=200, verbose_name='бренд звукової плати')),
                ('model', models.CharField(default='відсутній', max_length=200, verbose_name='модель звукової плати')),
                ('serial_number', models.CharField(default='відсутній', max_length=200, verbose_name='серійний номер')),
            ],
            options={
                'verbose_name': 'Звукова плата',
                'verbose_name_plural': 'Звукові плати',
            },
        ),
        migrations.CreateModel(
            name='VideoCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='відсутній', max_length=200, verbose_name='бренд відеокарти')),
                ('model', models.CharField(default='відсутній', max_length=200, verbose_name='модель відеокарти')),
                ('serial_number', models.CharField(default='відсутній', max_length=200, unique=True, verbose_name='серійний номер')),
                ('memory_size', models.IntegerField(default=0, verbose_name="обсяг пам'яті")),
            ],
            options={
                'verbose_name': 'Відеокарта',
                'verbose_name_plural': 'Відеокарти',
            },
        ),
        migrations.AlterModelManagers(
            name='motherboard',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='motherboard',
            name='form_factor',
            field=models.CharField(choices=[('не вказано', ''), ('ATX', 'ATX'), ('microATX', 'microATX'), ('Mini-ITX', 'Mini-ITX'), ('Nano-ITX', 'Nano-ITX'), ('Pico-ITX', 'Pico-ITX')], default='не вказано', max_length=20),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='type_ram_slot',
            field=models.CharField(choices=[('не вказано', ''), ('DIMM', 'DIMM'), ('RIMM', 'RIMM'), ('DDR DIMM', 'DDR DIMM'), ('DDR2', 'DDR2'), ('DDR3', 'DDR3')], default='не вказано', max_length=20),
        ),
        migrations.AddField(
            model_name='pc',
            name='power_supply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.fields.related.OneToOneField, to='IT_items.PowerSupply'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='serial_number',
            field=models.CharField(default='відсутній', max_length=200, unique=True, verbose_name='серійний номер'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='motherboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.fields.related.OneToOneField, to='IT_items.Motherboard'),
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='power_consumption',
            field=models.IntegerField(default=0, verbose_name='споживана потужність'),
        ),
        migrations.AddField(
            model_name='pc',
            name='lan_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.fields.related.OneToOneField, to='IT_items.LanCard'),
        ),
        migrations.AddField(
            model_name='pc',
            name='sound_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IT_items.SoundCard'),
        ),
        migrations.AddField(
            model_name='pc',
            name='video_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.fields.related.OneToOneField, to='IT_items.VideoCard'),
        ),
    ]
