# Generated by Django 3.0 on 2021-01-06 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IT_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='power_supply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IT_items.PowerSupply'),
        ),
    ]
