# Generated by Django 3.0 on 2021-01-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_items', '0003_motherboard_form_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='form_factor',
            field=models.CharField(choices=[('ATX', 'ATX'), ('microATX', 'microATX'), ('Mini-ITX', 'Mini-ITX'), ('Nano-ITX', 'Nano-ITX'), ('Pico-ITX', 'Pico-ITX')], default='', max_length=20),
        ),
    ]
