# Generated by Django 3.0 on 2021-03-15 08:55

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('IT_items', '0003_auto_20210315_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='sound_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.fields.related.OneToOneField, to='IT_items.SoundCard'),
        ),
    ]
