# Generated by Django 3.0 on 2021-04-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_items', '0005_auto_20210315_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='operating_system',
            field=models.CharField(choices=[('не вказано', ''), ('Windows 10', 'Windows 10'), ('Windows 7', 'Windows 7'), ('Windows XP', 'Windows XP'), ('Ubuntu', 'Ubuntu')], default='не вказано', max_length=20),
        ),
        migrations.AddField(
            model_name='pc',
            name='text_field',
            field=models.TextField(default='Місце для нотаток'),
        ),
    ]
