# Generated by Django 3.0 on 2021-01-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_items', '0006_auto_20210107_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherboard',
            name='type_ram_slot',
            field=models.CharField(choices=[('не вказано', ''), ('DIMM', 'DIMM'), ('RIMM', 'RIMM'), ('DDR DIMM', 'DDR DIMM'), ('DDR2', 'DDR2'), ('DDR3', 'DDR3')], default='не вказано', max_length=20),
        ),
    ]
