# Generated by Django 3.0 on 2021-04-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_items', '0006_auto_20210407_0646'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolidStateDrive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='відсутній', max_length=200, verbose_name='бренд материнської плати')),
                ('model', models.CharField(default='відсутній', max_length=200, verbose_name='модель материнської плати')),
                ('serial_number', models.CharField(default='відсутній', max_length=200, unique=True, verbose_name='серійний номер')),
                ('memory_size', models.IntegerField(default=0, verbose_name="обсяг пам'яті")),
            ],
            options={
                'verbose_name': 'Твердотільний накопичувач',
                'verbose_name_plural': 'Твердотільні накопичувачі',
            },
        ),
    ]
