# Generated by Django 3.0 on 2021-01-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_items', '0007_motherboard_type_ram_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='відсутній', max_length=200, verbose_name='бренд материнської плати')),
                ('model', models.CharField(default='відсутній', max_length=200, verbose_name='модель материнської плати')),
                ('serial_number', models.CharField(default='відсутній', max_length=200, verbose_name='серійний номер')),
                ('memory_size', models.IntegerField(default='невказано', verbose_name="обсяг пам'яті")),
            ],
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='serial_number',
            field=models.CharField(default='відсутній', max_length=200, verbose_name='серійний номер'),
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='serial_or_inventory_number',
            field=models.CharField(default='відсутній', max_length=200, verbose_name='серійний або інвентарний номер'),
        ),
    ]
