# Generated by Django 3.0 on 2021-04-08 13:07

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('IT_items', '0008_auto_20210407_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='hard_disk_drive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.fields.related.OneToOneField, to='IT_items.HardDiskDrive'),
        ),
        migrations.AddField(
            model_name='pc',
            name='solid_state_drive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.fields.related.OneToOneField, to='IT_items.SolidStateDrive'),
        ),
    ]
