# Generated by Django 3.0 on 2021-01-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_items', '0008_auto_20210115_0821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videocard',
            options={'verbose_name': 'Відео Карта', 'verbose_name_plural': 'Відео Карти'},
        ),
        migrations.AlterField(
            model_name='videocard',
            name='brand',
            field=models.CharField(default='відсутній', max_length=200, verbose_name='бренд відео карти'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='memory_size',
            field=models.IntegerField(default=0, verbose_name="обсяг пам'яті"),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='model',
            field=models.CharField(default='відсутній', max_length=200, verbose_name='модель відео карти'),
        ),
    ]
