# Generated by Django 3.0 on 2021-01-16 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IT_items', '0009_auto_20210116_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='video_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IT_items.VideoCard'),
        ),
    ]
