# Generated by Django 3.0 on 2021-01-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_items', '0010_pc_video_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='відсутній', max_length=200, verbose_name='бренд мережевої плати')),
                ('model', models.CharField(default='відсутній', max_length=200, verbose_name='модель мережевої плати')),
                ('serial_number', models.CharField(default='відсутній', max_length=200, verbose_name='серійний номер')),
            ],
            options={
                'verbose_name': 'Мережева плата',
                'verbose_name_plural': 'Мережеві плати',
            },
        ),
        migrations.AlterModelOptions(
            name='videocard',
            options={'verbose_name': 'Відеокарта', 'verbose_name_plural': 'Відеокарти'},
        ),
        migrations.AlterField(
            model_name='videocard',
            name='brand',
            field=models.CharField(default='відсутній', max_length=200, verbose_name='бренд відеокарти'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='model',
            field=models.CharField(default='відсутній', max_length=200, verbose_name='модель відеокарти'),
        ),
    ]
