# Generated by Django 3.0 on 2021-04-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_items', '0010_auto_20210408_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='place',
            field=models.IntegerField(default=0, null=True, verbose_name='номер учбового місця'),
        ),
    ]
