# Generated by Django 3.0 on 2021-01-17 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IT_items', '0011_auto_20210117_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='lan_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IT_items.LanCard'),
        ),
    ]
