# Generated by Django 3.0 on 2021-04-09 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT_items', '0011_auto_20210408_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opticaldrive',
            options={'verbose_name': 'Оптичний привод', 'verbose_name_plural': 'Оптичні приводи'},
        ),
    ]
