# Generated by Django 3.0 on 2021-04-09 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT_items', '0012_auto_20210409_0833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harddiskdrive',
            options={'verbose_name': 'Накопичувач на жорстких магнітних дисках', 'verbose_name_plural': 'Накопичувачі на жорстких магнітних дисках'},
        ),
    ]
