# Generated by Django 3.0 on 2021-01-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_items', '0012_pc_lan_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='відсутній', max_length=200, verbose_name='бренд звукової плати')),
                ('model', models.CharField(default='відсутній', max_length=200, verbose_name='модель звукової плати')),
                ('serial_number', models.CharField(default='відсутній', max_length=200, verbose_name='серійний номер')),
            ],
            options={
                'verbose_name': 'Звукова плата',
                'verbose_name_plural': 'Звукові плати',
            },
        ),
        migrations.AlterModelManagers(
            name='motherboard',
            managers=[
            ],
        ),
    ]
