# Generated by Django 3.0 on 2021-01-21 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IT_items', '0013_auto_20210121_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='sound_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IT_items.SoundCard'),
        ),
    ]
