# Generated by Django 3.0 on 2021-04-16 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT_items', '0014_motherboard_central_processing_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc',
            name='text_field',
        ),
    ]
