# Generated by Django 3.0 on 2021-01-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_items', '0014_pc_sound_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='serial_number',
            field=models.CharField(max_length=200, unique=True, verbose_name='серійний номер'),
        ),
    ]
