# Generated by Django 3.0 on 2021-04-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_items', '0015_remove_pc_text_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number_pc', models.CharField(max_length=200, verbose_name="інвентарний номер персонального комп'ютера")),
            ],
            options={
                'verbose_name': 'Акт проведеної роботи',
                'verbose_name_plural': 'Акти проведених робіт',
            },
        ),
    ]
