# Generated by Django 3.0 on 2021-01-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_items', '0016_auto_20210127_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powersupply',
            name='power_consumption',
            field=models.IntegerField(default=0, verbose_name='споживана потужність'),
        ),
    ]
