# Generated by Django 3.0 on 2021-04-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_items', '0016_workreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='workreport',
            name='work_report_field',
            field=models.TextField(default='Опис проведених робіт'),
        ),
    ]
