# Generated by Django 3.0 on 2021-01-27 09:16

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('IT_items', '0017_auto_20210127_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='power_supply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.fields.related.OneToOneField, to='IT_items.PowerSupply'),
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='serial_or_inventory_number',
            field=models.CharField(default='відсутній', max_length=200, unique=True, verbose_name='серійний або інвентарний номер'),
        ),
    ]
