# Generated by Django 3.0 on 2021-01-27 09:17

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('IT_items', '0019_auto_20210127_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='power_supply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.fields.related.OneToOneField, to='IT_items.PowerSupply'),
        ),
    ]
