# Generated by Django 3.0 on 2021-01-27 09:36

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('IT_items', '0020_auto_20210127_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='video_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.fields.related.OneToOneField, to='IT_items.VideoCard'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='serial_number',
            field=models.CharField(default='відсутній', max_length=200, unique=True, verbose_name='серійний номер'),
        ),
    ]
