# Generated by Django 3.0 on 2021-01-27 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IT_items', '0023_auto_20210127_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='motherboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IT_items.Motherboard'),
        ),
    ]
