# Generated by Django 3.0 on 2021-01-27 10:09

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('IT_items', '0024_auto_20210127_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='motherboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.fields.related.OneToOneField, to='IT_items.Motherboard'),
        ),
    ]
